### PR TITLE
OCI-1043 OCI-1044 added possibility for consent management

### PR DESCRIPTION
**Pull request by PMartins03**

### CODE REVIEW

**Comment by ErickRaidiam** [comment]
Everything looks good to me, however i would suggest we do two changes here to make it clear for the user that he can indeed call and have multiple consents.

Above the selected consent status i would add:

image

a field called "Selected Consent ID: XXXX" so the user understand that he is seeing the details of that consent.

Additionally, the consents button should be renamed "Manage Consents" and it should be displayed at the right side of the client details 

image

**Comment by PMartins03** [comment]
image

**Comment by ErickRaidiam** [comment]
That's perfect. All good on my side from an UI and usage POV!

**Comment by milad-raidiam** [comment]
Everything looks good to me. The only two changes I would recommend would be to change the 'remove' button text to 'delete'. Also when you delete a consent, you said the first consent id gets selected, but it's not clear that it's selected, so I think it would be better to actually select that programmatically.

**Pull request merged**
